<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Template.Domain\Template.Domain.csproj" />
    </ItemGroup>

</Project>
